Interesting documentation about Python COM Objects that needs especial parameters / arguments .
https://pythonhosted.org/comtypes/#using-com-objects

Mates Types table
http://help.solidworks.com/2017/english/api/sldworksapi/Get_Mates_Example_VB.htm

Mate Entity Array Table
http://help.solidworks.com/2018/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.imateentity2~entityparams.html

IModelDoC2 Members Page http://help.solidworks.com/2018/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html
Mates Types swMateType_e Enumeration http://help.solidworks.com/2018/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swMateType_e.html

IMate2 Interface Members Page http://help.solidworks.com/2018/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IMate2_members.html
IMateEntity2 Interface Members Page http://help.solidworks.com/2018/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IMateEntity2_members.html

Part Object IComponent2
https://help.solidworks.com/2013/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IComponent2_members.html

Class hierarchy
https://www.codestack.net/solidworks-api/getting-started/api-object-model/class-diagram/

Manipulator Method to study
https://help.solidworks.com/2019/english/api/swpublishedapi/SolidWorks.interop.swpublished~SolidWorks.interop.swpublished.ISwManipulatorHandler2.html

Way to save stl automatically
http://help.solidworks.com/2017/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.imodeldocextension~saveas.html#_ga=2.72973840.2077313738.1576276171-9d70c8a0-0ac9-11ea-813d-c90d4ca52510
-------------------------------------------------------------------------
IMathTransform Interface Members
Maybe this object can set transformation to parts

Get Name For selection
Maybe a possibility to solver "by name" argument bug in"get transformation by name" object
https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature~GetNameForSelection.html

PresentationTransform Property (IComponent2)
https://help.solidworks.com/2017/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IComponent2~PresentationTransform.html
